### ISSUE TITLE
WR Technique P2R

### ISSUE THREAD

**Issue by BenoitGeslain** [BenoitGeslain/Visuo-haptic-Illusions-Toolkit#14]
P2R, Thomas and Rosenburg, 2019 : https://ieeexplore.ieee.org/document/8797983

**Comment by bjrtx** [comment]
Created first implementation of central-difference gradient for use in upcoming PR.

**Comment by BenoitGeslain** [comment]
Issues with casting to and from Vector2 and Vector3 fixed in https://github.com/BenoitGeslain/Visuo-haptic-Illusions-Toolkit/commit/2d19bc56fa31dd5e4527aa453e97433df95bbbd5 by using Vector3 only in 3D.
