### ISSUE TITLE
Add clickable url links in tooltips

### ISSUE THREAD

**Issue by BenoitGeslain** [BenoitGeslain/Visuo-haptic-Illusions-Toolkit#16]
For example in paramtersToolkit.cs, users should be able to click on a link inside the tooltip

**Comment by bjrtx** [comment]
As per https://www.foundations.unity.com/components/tooltip '[t]ooltips are transient, concise, and easily scanned.' The preferred solution seems to be link labels pointing to out-of-editor documentation.

**Comment by bjrtx** [comment]
Either https://docs.unity3d.com/ScriptReference/EditorGUILayout.LinkButton.html or https://docs.unity3d.com/ScriptReference/EditorGUI.LinkButton.html ought to be relevant here
