### ISSUE TITLE
Record Class Scene is considered a function in doxygen doc

### ISSUE THREAD

**Issue by BenoitGeslain** [BenoitGeslain/Visuo-haptic-Illusions-Toolkit#51]
See https://benoitgeslain.github.io/Visuo-haptic-Illusions-Toolkit/namespaceVHToolkit_1_1Redirection.html#aa3ec964b2baf3fc23c0b779c89dafea1.

**Comment by bjrtx** [comment]
Seems to be a function, see https://github.com/BenoitGeslain/Visuo-haptic-Illusions-Toolkit/blob/60247197d3393ccea579680feb7a7b9e498d42c5/Visuo-haptic%20Toolkit/Assets/Visuo-Haptic%20Toolkit/Scripts/Redirection/Scene.cs#L42C1

Don't remember why that is
