### ISSUE TITLE
APF - Set physical environment using Guardian

### ISSUE THREAD

**Issue by BenoitGeslain** [BenoitGeslain/Visuo-haptic-Illusions-Toolkit#58]

**Comment by bjrtx** [comment]
Support for accessing the Guardian's outer boundary seems deprecated in favour of rectangular boundaries, see
- https://communityforums.atmeta.com/t5/Unity-VR-Development/Work-with-guardian-outer-boundary-when-using-openXR/td-p/1014675
- https://developer.oculus.com/documentation/unity/unity-ovrboundary/

Any solution to this issue thus runs the risk of quick obsolescence.
